### ISSUE TITLE
Issue with example_5.14_of_section_5.2

### ISSUE THREAD

**Issue by abrenaut** [WinVector/zmPDSwR#12]
Hi, I'm working through the book and I have an issue with the following example: [00070_example_5.14_of_section_5.2.5.R](https://github.com/WinVector/zmPDSwR/blob/master/CodeExamples/c05_Choosing_and_evaluating_models/00070_example_5.14_of_section_5.2.5.R)

When running `outer(1:n,1:n,function(a,b) d[a,'cluster'])` I get the following error `Error in dim(robj) <- c(dX, dY) : dims [product 529] do not match the length of object [1]`.

I'm not using the original dataset but my data has the same format.

Re-writing the code this way fixes the issue

```
n <- dim(d)[[1]]
pairs <- merge(1:n,1:n,all=TRUE)
names(pairs) <- c("a", "b")
pairs$ca <- d[pairs$a,'cluster'][[1]]
pairs$cb <- d[pairs$b,'cluster'][[1]]
pairs$dist <- sqrt((d[pairs$a,'x']-d[pairs$b,'x'])^2 + (d[pairs$a,'y']-d[pairs$b,'y'])^2)[[1]]

dcast(pairs,ca~cb,value.var='dist',mean)
```

**Comment by JohnMount** [comment]
Thanks, definitely like your code better (including the merge).  We'll try to fix the example.
