### ISSUE TITLE
F1 score in accuracyMeasures

### ISSUE THREAD

**Issue by singularperturbation** [WinVector/zmPDSwR#6]
Hi!  Working my way through the book (love it so far!) and I had a question about how the F1 score is calculated in the accuracyMeasures function (https://github.com/WinVector/zmPDSwR/blob/672cfacdb24b6f7ab2797af326d0421668392a06/CodeExamples/c09_Exploring_advanced_methods/00165_example_9.1_of_section_9.1.1.R#L28).

In Listing 9.1, it says that f1 is the product of precision and recall, which is how it's implemented in the code.  Looking elsewhere, I see F1 defined as the harmonic mean or weighted average of precision and recall:
https://en.wikipedia.org/wiki/F1_score
http://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html

I didn't find anything in the errata, so I wanted to make sure that this was deliberate.  Are there different definitions for the F1 score, or should I use a weighted average for F1 score in my code?

**Comment by NinaZumel** [comment]
Whoops! You are right; that code is incorrect. F1 is in fact the harmonic mean. It is correctly defined on page 96 (Chapter 5). Thanks for catching that! We are fixing the code and adding it to the errata now.

Regards,
Nina

--------------------
Nina Zumel
Win-Vector, LLC
http://www.win-vector.com/ <http://www.win-vector.com/>
http://www.win-vector.com/blog/ <http://www.win-vector.com/blog/>
Our book: Practical Data Science with R http://www.manning.com/zumel/ <http://www.manning.com/zumel/>
Twitter: https://twitter.com/WinVectorLLC <https://twitter.com/WinVectorLLC>
nzumel@win-vector.com <mailto:nzumel@win-vector.com>

**Comment by singularperturbation** [comment]
Awesome!  Thanks for getting back so quickly!
