### ISSUE TITLE
found issue in the function

### ISSUE THREAD

**Issue by moongou** [WinVector/zmPDSwR#8]
Here,in chapter 6,there is a function I think something wrong.
while "pPosWna <- (naTab/sum(naTab))[pos]  "can't get the stat that we want,
We really want the result is positive proportions,but the results are the negative ones.
have a try ,hope your answers,thanks.

mkPredC <- function(outCol,varCol,appCol) {     # Note: 1 
   pPos <- sum(outCol==pos)/length(outCol)  # Note: 2 
   naTab <- table(as.factor(outCol[is.na(varCol)]))
   pPosWna <- (naTab/sum(naTab))[pos]   # Note: 3 
   vTab <- table(as.factor(outCol),varCol)
   pPosWv <- (vTab[pos,]+1.0e-3*pPos)/(colSums(vTab)+1.0e-3)    # Note: 4 
   pred <- pPosWv[appCol]   # Note: 5 
   pred[is.na(appCol)] <- pPosWna   # Note: 6 
   pred[is.na(pred)] <- pPos    # Note: 7 
   pred     # Note: 8 
}

**Comment by moongou** [comment]
I rewrite the function bellow:

mkPredC <- function(outCol,varCol,appCol) {     # Note: 1 
  pPos <- sum(outCol==pos)/length(outCol)  # Note: 2 
  naTab <- table(as.factor(outCol[is.na(varCol)]))
  
  **#the following 3 lines is written by me,then it can run normally。**
  na.dataframe <- as.data.frame(naTab)
  names(na.dataframe) <- c('pos.or.neg','Freq')
  pPosWna <- (na.dataframe$Freq[na.dataframe$pos.or.neg ==pos])/ sum(na.dataframe$Freq)

  vTab <- table(as.factor(outCol),varCol)
  
  **#the following 2 lines is written by me,then it can run normally。**
  v.dataframe <- as.data.frame(vTab)
  pPosWv <-  subset(v.dataframe,Var1==pos)[,"Freq"]/colSums(vTab)

  pred <- pPosWv[appCol]   # Note: 5 
  pred[is.na(appCol)] <- pPosWna   # Note: 6 
  pred[is.na(pred)] <- pPos    # Note: 7 
  pred     # Note: 8 
}

**Comment by moongou** [comment]
Then ,I meet another wrong bellow:
> for(v in catVars) {
+   pi <- paste('pred',v,sep='')
+   dTrain[,pi] <- mkPredC(dTrain[,outcome],dTrain[,v],dTrain[,v])
+   dCal[,pi] <- mkPredC(dTrain[,outcome],dTrain[,v],dCal[,v])
+   dTest[,pi] <- mkPredC(dTrain[,outcome],dTrain[,v],dTest[,v])
+ }
Error in names(na.dataframe) <- c("pos.or.neg", "Freq") : 
  'names' attribute [2] must be the same length as the vector [1]

**Comment by moongou** [comment]
then ,this is really working OK!

mkPredC <- function(outCol,varCol,appCol) {     # Note: 1 
  pPos <- sum(outCol==pos)/length(outCol)  # Note: 2 
  if (sum(is.na(dTrain$Var226))==0) pPosWna<-0 else {
      naTab <- table(as.factor(outCol[is.na(varCol)]))
      #the following 3 lines is written by me,then it can run normally。
      na.dataframe <- as.data.frame(naTab)
      names(na.dataframe) <- c('pos.or.neg','Freq')
      pPosWna <- (na.dataframe$Freq[na.dataframe$pos.or.neg ==pos])/ sum(na.dataframe$Freq)
    }
  vTab <- table(as.factor(outCol),varCol)
  
  #the following 2 lines is written by me,then it can run normally。
  v.dataframe <- as.data.frame(vTab)
  pPosWv <-  subset(v.dataframe,Var1==pos)[,"Freq"]/colSums(vTab)

  pred <- pPosWv[appCol]   # Note: 5 
  pred[is.na(appCol)] <- pPosWna   # Note: 6 
  pred[is.na(pred)] <- pPos    # Note: 7 
  pred     # Note: 8 
}

**Comment by moongou** [comment]
OK,I know the reason why the very small value added .that is used as smooth parameter.

**Comment by JohnMount** [comment]
I am sorry you had trouble.  But I think I understand and found the problem.  

If the outcome variable takes on values from c(TRUE,FALSE) (i.e. logical) then the line with note 4 "vTab[pos,]" doesn't convert the table into a usable row as intended (due to the irregularity of the [,] operator).  In our example the target class was deliberately a string so all works as expected.  So the work around is make sure you are using a string or factor for the value to be predicted, not a logical.

`
> table(c(TRUE,FALSE,FALSE),c('a','a','b'))[TRUE,] # incorrect, table return not a row 
       
        a b
  FALSE 1 1
  TRUE  1 0
> table(c(TRUE,FALSE,FALSE),c('a','a','b'))['TRUE',] # correct, we get a row
a b 
1 0 
`

So I'd say it is a problem with R's table function subscript.
